theme: jekyll-theme-cayman
title: octaValidate homepage
description: This Tiny Script helps to validate your HTML forms using validation rules, sophisticated regular expressions and form input attributes.